[tool.poetry]
name = "kursovaya_3"
version = "0.1.0"
description = "Проект для работы с API вакансий HH.ru и хранения данных в файле."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
